export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    HO_SPV: 'HO_SPV',
    WAREHOUSE_HEAD: 'WAREHOUSE_HEAD',
    COORDINATOR_WH: 'COORDINATOR_WH',
    WAREHOUSE_ADMIN: 'WAREHOUSE_ADMIN',
    FINANCE_USER: 'FINANCE_USER',
    FIELD_USER: 'FIELD_USER',
    VIEWER: 'VIEWER',
};